options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Passo 1: Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA', '.']
    
  # Passo 2: Envia a imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA']

  # Passo 3: Criar o Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'create'
      - 'infograficos' # Substitua pelo nome desejado para o seu job
      - '--image'
      - 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA'
      - '--region'
      - 'us-east4'
      - '--set-cloudsql-instances'
      - 'infograficos-prd:us-east4:infograficos'
      - '--vpc-connector'
      - 'cloudrun-cloudsql' # Nome do  VPC Connector
      - '--set-env-vars'
      - 'DB_USER=$$DB_USER,DB_PASS=$$DB_PASS,DB_NAME=$$DB_NAME,INSTANCE_CONNECTION_NAME=infograficos-prd:us-east4:infograficos'
      - '--max-retries'
      - '0'
    id: 'create-job'
    secretEnv: ['DB_USER', 'DB_PASS', 'DB_NAME']
    
  # Passo 4: Executar o Job imediatamente após a criação (Opcional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'execute'
      - 'infograficos' # Deve corresponder ao nome do job criado na etapa anterior
      - '--region'
      - 'us-east4'
    id: 'execute-job'
    waitFor:
      - 'create-job'

images:
  - 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA'
  
availableSecrets:
  secretManager:
    - versionName: projects/1073591577692/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/1073591577692/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/1073591577692/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'
