options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA', '.']
    
  # Passo 2: Enviar a imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA']

  # Passo 3: Fazer o deploy da imagem no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'teste-gcp',
           '--image', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA',
           '--region', 'us-east4',
           '--platform', 'managed',
           '--allow-unauthenticated']
           #--set-env-vars, 'PORT=8080, DB_USER=usuario, DB_PASS=senha, INSTANCE_CONNECTION_NAME=project:region:instance'

# Especificar quais imagens devem ser armazenadas após o build
images:
  - 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA'
  
# logsBucket: 'gs://cloudbuildlogs2024'
#options:
#  logging: GCS_ONLY
# logging: CLOUD_LOGGING_ONLY
