options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  
steps:
  # Passo 1: Build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA', '.']
    
  # Passo 2: Send to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA']

  # Passo 3: Create cloud run job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud beta run jobs create infograficos \
      --image=gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA \
      --region=us-east4 \
      --set-cloudsql-instances=infograficos-prd:us-east4:infograficos \
      --vpc-connector=cloudrun-cloudsql \
      --set-env-vars=DB_USER=$$DB_USER,DB_PASS=$$DB_PASS,DB_NAME=$$DB_NAME,INSTANCE_CONNECTION_NAME=infograficos-prd:us-east4:infograficos \
      --max-retries=0 \
      --execute-now
    secretEnv: ['DB_USER', 'DB_PASS', 'DB_NAME']

images:
  - 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA'
  
availableSecrets:
  secretManager:
    - versionName: projects/infograficos-prd/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/infograficos-prd/secrets/DB_PASS/versions/latest
      env: 'DB_PASS'
    - versionName: projects/infograficos-prd/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'
      
